---
- name: allow only swarm hosts connections to swarm node discovery service
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ docker_swarm_node_discovery_port }}"
    jump: ACCEPT
    comment: "from ansible docker swarm node discovery role"
